services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app_container
    volumes:
      - .:/app  # ローカルのカレントディレクトリをコンテナの/appディレクトリにマウント
    ports:
      - "8080:8080"  # ローカルポート8080をコンテナのポート8080にマッピング
    # command: /bin/bash -c "tail -f /dev/null"