services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app_container
    volumes:
      - .:/app  # ローカルのカレントディレクトリをコンテナの/appディレクトリにマウント
    ports:
      - "8000:8000"  # ローカルポート8000をコンテナのポート8000にマッピング
    command: /bin/bash -c "tail -f /dev/null"